version: '3'
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./postgresql/data
    ports:
      - 5432:5432